name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Create artifact
        run: |
          hugo new site quickstart
          cd quickstart
          git init
          git submodule add  https://github.com/nunocoracao/blowfish.git themes/blowfish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: quickstart
