name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          wget https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
          tar -xf go1.23.0.linux-amd64.tar.gz 
          sudo mv go /usr/local/
          export PATH=$PATH:/usr/local/go/bin
          go version
          
          CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
          hugo version

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifact
      #     path: hugo/
