name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          mkdir output
          echo "Build results" > output/build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output/

  test:
    runs-on: ubuntu-latest
    needs: build  # Rely on the build job

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./

      - name: Verify artifact
        run: ls